language: shell
os:
  - osx
  - linux
osx_image: xcode11.2
dist: xenial
env:
  - SWIFT_VERSION=5.1
  - SWIFT_VERSION=5.1.2
cache:
  directories:
    - $HOME/.swiftenv
install: 
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
jobs:
  include:
    - os: linux
      dist: bionic
      env: SWIFT_VERSION=5.1
    - os: linux
      dist: bionic
      env: SWIFT_VERSION=5.1.2
